/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:917e0d17-48d9-4ecb-8e10-db93863dd6ed",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_YAfpVSAAB",
    "aws_user_pools_web_client_id": "660m51gg2mti7u1a0idh4oq02q",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://f4liql4ubva2nhpecu4chlvvve.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-f64s5hon4bdudfzzk32dbitove",
    "aws_user_files_s3_bucket": "my-first-bucket233837-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
